// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_identity_data.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserIdentityData_Unit int32

const (
	UserIdentityData_ID       UserIdentityData_Unit = 0
	UserIdentityData_LOGIN    UserIdentityData_Unit = 1
	UserIdentityData_EMAIL    UserIdentityData_Unit = 2
	UserIdentityData_PHONE    UserIdentityData_Unit = 3
	UserIdentityData_PASSWORD UserIdentityData_Unit = 4
)

var UserIdentityData_Unit_name = map[int32]string{
	0: "ID",
	1: "LOGIN",
	2: "EMAIL",
	3: "PHONE",
	4: "PASSWORD",
}

var UserIdentityData_Unit_value = map[string]int32{
	"ID":       0,
	"LOGIN":    1,
	"EMAIL":    2,
	"PHONE":    3,
	"PASSWORD": 4,
}

func (x UserIdentityData_Unit) String() string {
	return proto.EnumName(UserIdentityData_Unit_name, int32(x))
}

func (UserIdentityData_Unit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_436f96e9a9501d63, []int{0, 0}
}

type UserIdentityData struct {
	Value                uint64                `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Unit                 UserIdentityData_Unit `protobuf:"varint,2,opt,name=unit,proto3,enum=auth.UserIdentityData_Unit" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserIdentityData) Reset()         { *m = UserIdentityData{} }
func (m *UserIdentityData) String() string { return proto.CompactTextString(m) }
func (*UserIdentityData) ProtoMessage()    {}
func (*UserIdentityData) Descriptor() ([]byte, []int) {
	return fileDescriptor_436f96e9a9501d63, []int{0}
}

func (m *UserIdentityData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIdentityData.Unmarshal(m, b)
}
func (m *UserIdentityData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIdentityData.Marshal(b, m, deterministic)
}
func (m *UserIdentityData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIdentityData.Merge(m, src)
}
func (m *UserIdentityData) XXX_Size() int {
	return xxx_messageInfo_UserIdentityData.Size(m)
}
func (m *UserIdentityData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIdentityData.DiscardUnknown(m)
}

var xxx_messageInfo_UserIdentityData proto.InternalMessageInfo

func (m *UserIdentityData) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *UserIdentityData) GetUnit() UserIdentityData_Unit {
	if m != nil {
		return m.Unit
	}
	return UserIdentityData_ID
}

func init() {
	proto.RegisterEnum("auth.UserIdentityData_Unit", UserIdentityData_Unit_name, UserIdentityData_Unit_value)
	proto.RegisterType((*UserIdentityData)(nil), "auth.UserIdentityData")
}

func init() { proto.RegisterFile("user_identity_data.proto", fileDescriptor_436f96e9a9501d63) }

var fileDescriptor_436f96e9a9501d63 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x2d, 0x4e, 0x2d,
	0x8a, 0xcf, 0x4c, 0x49, 0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0x8c, 0x4f, 0x49, 0x2c, 0x49, 0xd4, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2c, 0x2d, 0xc9, 0x50, 0x9a, 0xc1, 0xc8, 0x25, 0x10,
	0x5a, 0x9c, 0x5a, 0xe4, 0x09, 0x55, 0xe1, 0x92, 0x58, 0x92, 0x28, 0x24, 0xc2, 0xc5, 0x5a, 0x96,
	0x98, 0x53, 0x9a, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x12, 0x04, 0xe1, 0x08, 0xe9, 0x73, 0xb1,
	0x94, 0xe6, 0x65, 0x96, 0x48, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x19, 0x49, 0xeb, 0x81, 0xf4, 0xeb,
	0xa1, 0xeb, 0xd5, 0x0b, 0xcd, 0xcb, 0x2c, 0x09, 0x02, 0x2b, 0x54, 0xb2, 0xe5, 0x62, 0x01, 0xf1,
	0x84, 0xd8, 0xb8, 0x98, 0x3c, 0x5d, 0x04, 0x18, 0x84, 0x38, 0xb9, 0x58, 0x7d, 0xfc, 0xdd, 0x3d,
	0xfd, 0x04, 0x18, 0x41, 0x4c, 0x57, 0x5f, 0x47, 0x4f, 0x1f, 0x01, 0x26, 0x10, 0x33, 0xc0, 0xc3,
	0xdf, 0xcf, 0x55, 0x80, 0x59, 0x88, 0x87, 0x8b, 0x23, 0xc0, 0x31, 0x38, 0x38, 0xdc, 0x3f, 0xc8,
	0x45, 0x80, 0x25, 0x89, 0x0d, 0xec, 0x4e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x30, 0xbf,
	0x11, 0x2c, 0xc3, 0x00, 0x00, 0x00,
}
