// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user_identity_data.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserIdentityData struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login                string   `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserIdentityData) Reset()         { *m = UserIdentityData{} }
func (m *UserIdentityData) String() string { return proto.CompactTextString(m) }
func (*UserIdentityData) ProtoMessage()    {}
func (*UserIdentityData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8310ae0b5945b955, []int{0}
}

func (m *UserIdentityData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIdentityData.Unmarshal(m, b)
}
func (m *UserIdentityData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIdentityData.Marshal(b, m, deterministic)
}
func (m *UserIdentityData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIdentityData.Merge(m, src)
}
func (m *UserIdentityData) XXX_Size() int {
	return xxx_messageInfo_UserIdentityData.Size(m)
}
func (m *UserIdentityData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIdentityData.DiscardUnknown(m)
}

var xxx_messageInfo_UserIdentityData proto.InternalMessageInfo

func (m *UserIdentityData) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserIdentityData) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *UserIdentityData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserIdentityData) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserIdentityData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*UserIdentityData)(nil), "auth.UserIdentityData")
}

func init() { proto.RegisterFile("proto/user_identity_data.proto", fileDescriptor_8310ae0b5945b955) }

var fileDescriptor_8310ae0b5945b955 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2d, 0x4e, 0x2d, 0x8a, 0xcf, 0x4c, 0x49, 0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0x8c,
	0x4f, 0x49, 0x2c, 0x49, 0xd4, 0x03, 0x4b, 0x08, 0xb1, 0x24, 0x96, 0x96, 0x64, 0x28, 0x35, 0x30,
	0x72, 0x09, 0x84, 0x16, 0xa7, 0x16, 0x79, 0x42, 0x55, 0xb8, 0x24, 0x96, 0x24, 0x0a, 0xf1, 0x71,
	0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x89, 0x70,
	0xb1, 0xe6, 0xe4, 0xa7, 0x67, 0xe6, 0x49, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x20,
	0xd1, 0xd4, 0xdc, 0xc4, 0xcc, 0x1c, 0x09, 0x66, 0x88, 0x28, 0x98, 0x03, 0x12, 0x2d, 0xc8, 0xc8,
	0xcf, 0x4b, 0x95, 0x60, 0x81, 0x88, 0x82, 0x39, 0x42, 0x52, 0x5c, 0x1c, 0x05, 0x89, 0xc5, 0xc5,
	0xe5, 0xf9, 0x45, 0x29, 0x12, 0xac, 0x60, 0x09, 0x38, 0x3f, 0x89, 0x0d, 0xec, 0x1e, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x17, 0x6b, 0x7e, 0x82, 0xb1, 0x00, 0x00, 0x00,
}
